version: '3.8'

services:
  backend:
    build: .
    container_name: financial-system-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financeApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - financial-network

  db:
    image: postgres:13
    container_name: financial-system-db
    environment:
      POSTGRES_DB: financeApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - financial-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  financial-network:
    driver: bridge

volumes:
  postgres_data:
